baseURL = 'https://hewerthomn.com/'
author = 'Éverton Inocêncio'

languageCode = 'br'
defaultContentLanguage = 'br'

theme = 'anatole'
publishDir = 'dist'

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
# disqusShortname = "hewerthomn"
