baseURL = 'https://hewerthomn.com/'
languageCode = 'en-us'
author = 'Éverton Inocêncio'
theme = 'anatole'
profilePicture = "images/profile.jpg"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"