baseURL: https://hewerthomn.com

languageCode: br
defaultContentLanguage: br
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
titleCaseStyle: none

theme: anatole
publishDir: dist
# cleanDestinationDir: true

# summaryLength: 10
enableEmoji: true
enableRobotsTXT: true
watch: true

# Syntax highlighting
pygmentsUseClasses: true   
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true

taxonomies:
  category: categories
  series: series
  tag: tags

params:
  title: 'Éverton Inocêncio'
  author: 'Éverton Inocêncio'
  profilePicture: images/profile.jpg
  keywords: "hewerthomn, tonton, éverton inocencio,"
  favicon: 'favicons/'
  doNotLoadAnimations: false
  readMore: true
  fullPostContent: true

  # postSectionName: blog

  mainSections: ['posts']
  images: ["images/site-feature-image.png"]

  contactFormAction: https://formspree.io/f/mleqpjgp
  contactFormReCaptcha: 6Lf9AagpAAAAACAXnhqPvZ7l-tk6XlIFNJ7MX2pu

  gtagId: G-N71B9TETZQ

  socialIcons:
    - title: GitHub
      icon: 'fa-brands fa-github'
      url: 'https://github.com/hewerthomn/'

    - title: LinkedIn
      icon: 'fa-brands fa-linkedin'
      url: 'https://www.linkedin.com/in/everton-inocencio/'

    - title: Instagram
      icon: 'fa-brands fa-instagram'
      url: 'https://www.instagram.com/hewerthomn'

    - title: Vimeo
      icon: 'fa-brands fa-vimeo'
      url: https://www.vimeo.com/hewerthomn

  # Google Fonts
  #googleFonts: ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]

  # Google Site Verify
  #googleSiteVerify: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

  # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'
  reversepagetitle: true
  hidesidebar: false

  # utterances:
  #   repo: hewerthomn/hewerthomn.github.io
  #   issueTerm: pathname
  #   theme: preferred-color-scheme

## Enable Disqus
disqusShortname: hewerthomn

languages:

  br:
    weight: 1
    title: Meu Blog
    languageCode: br
    languageName: BRASILEIRO
    params:
      description: |
        Desenvolvedor de software
        De Rondônia, Brasil
    menus:
      main:
        - name: Início
          weight: 10
          url: /
        - name: Blog
          weight: 20
          url: /posts/
        - name: Portfólio
          weight: 30
          url: /portfolio/
        - name: Contato
          weight: 40
          url: /contact/
        - name: Sobre
          weight: 50
          url: /about/

  # en:
  #   weight: 2
  #   title: My Blog
  #   languageCode: en
  #   languageName: ENGLISH
  #   params:
  #     description: |
  #       Software developer
  #       From Rondonia, Brazil
  #   menus:
  #     main:
  #       - name: Home
  #         weight: 10
  #         url: /en/
  #       - name: Blog
  #         weight: 20
  #         url: /en/posts/
  #       - name: Portfolio
  #         weight: 30
  #         url: /en/portfolio/
  #       - name: Contact
  #         weight: 40
  #         url: /en/contact/
  #       - name: About
  #         weight: 50
  #         url: /en/about/