[br]
weight = 1
title = "Meu blog"
languageName = "BR"
languageCode = 'pt-BR'

[br.params]
description = """
Desenvolvedor de software
De Rondônia, Brasil
"""

[en]
weight = 2
title = "My blog"
languageName = "EN"
languageCode = 'en-US'

[en.params]
description = """
Software developer
From Rondonia, Brazil
"""