[[main]]
name = "Projetos"
weight = 200
identifier = "projects"
url = "/projetos/"

[[main]]
name = "Portfolio"
weight = 300
identifier = "portfolio"
url = "/portfolio/"

[[main]]
name = "Sobre"
weight = 400
identifier = "about"
url = "/sobre/"
