[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/hewerthomn/"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/everton-inocencio/"

[[socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/hewerthomn"
