title = "Éverton Inocêncio"
author = "Éverton Inocêncio"

#copyright = "2020-2021"
description = """
Software developer
From Rondônia, Brazil
"""
profilePicture = "images/profile.jpg"
keywords = "hewerthomn, tonton, éverton inocencio,"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = ["css/custom.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = []
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false

# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/mleqpjgp"
#contactFormReCaptcha = "your-site-key-here"

# Google Analytics
gtagId = "G-N71B9TETZQ"

[utterances]
repo = "hewerthomn/hewerthomn.github.io"
issueTerm = "pathname"
theme= "preferred-color-scheme"
# label =

# [umami]
# serverURL = "https://analytics.us.umami.is"
# id = "6b90e81f-e77f-4791-9381-d158766d2fec"
# trackerScriptName = "script.js"

# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]

# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"

# Read More links for truncated summaries
readMore = true
postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

hidesidebar = false

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/hewerthomn/"

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/everton-inocencio/"

[[socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/hewerthomn"
